In [1]:
import pandas as pd

crime_df = pd.read_csv("crime2024_with_zipcodes.csv")
school_df = pd.read_csv("school_quality_ratings.csv")
zip_df = pd.read_csv("zip_neighborhoods.csv")

# Rename ZIP columns if needed
crime_df = crime_df.rename(columns={'zipcode': 'ZIP Code'})

school_zip_merged = pd.merge(school_df, zip_df, on='ZIP Code', how='inner')

final_merged_df = pd.merge(school_zip_merged, crime_df, on='ZIP Code', how='left')

In [12]:
final_merged_df.head()

,School Name,Quality Score,Letter Grade,ZIP Code,Academic Score,Resources Score,Equity Score,Outcomes Score,Strengths,Areas for Improvement,...,LocationType,press_release,social_media,Beat,NhoodName,DISTRICT,NPU,GlobalID,x,y
0,ASA HILLIARD ELEMENTARY SCHOOL,21.5,F,30344,24.0,17.0,18.0,25.0,"Academic, Outcomes","Resources, Equity",...,RESIDENCE_HOME,NaN,NaN,411.0,Greenbriar,11.0,R,897a1a1c-57a4-41dd-962c-37d71f8aa801,-84.495048,33.668151
1,ASA HILLIARD ELEMENTARY SCHOOL,21.5,F,30344,24.0,17.0,18.0,25.0,"Academic, Outcomes","Resources, Equity",...,RESIDENCE_HOME,NaN,NaN,414.0,NaN,11.0,P,2ef9f6f2-b884-448f-ae4f-92d1436b7271,-84.500712,33.668401
2,ASA HILLIARD ELEMENTARY SCHOOL,21.5,F,30344,24.0,17.0,18.0,25.0,"Academic, Outcomes","Resources, Equity",...,RESIDENCE_HOME,NaN,NaN,410.0,Campbellton Road,11.0,R,054a5ef1-16ff-4005-adbc-feaaf2921131,-84.459940,33.699990
3,ASA HILLIARD ELEMENTARY SCHOOL,21.5,F,30344,24.0,17.0,18.0,25.0,"Academic, Outcomes","Resources, Equity",...,RESIDENCE_HOME,NaN,NaN,411.0,Greenbriar,11.0,R,ab37727b-0716-4e6d-9276-1f8a853b3e7c,-84.490358,33.684707
4,ASA HILLIARD ELEMENTARY SCHOOL,21.5,F,30344,24.0,17.0,18.0,25.0,"Academic, Outcomes","Resources, Equity",...,RESIDENCE_HOME,NaN,NaN,410.0,Campbellton Road,11.0,R,c647ee86-18a5-480e-98ef-ed55a7f92321,-84.459940,33.699990

In [3]:
final_merged_df.shape

(252188, 48)

In [4]:
final_merged_df.describe()

,Quality Score,ZIP Code,Academic Score,Resources Score,Equity Score,Outcomes Score,Population(2024),Averge house price,crime,crime_density,...,ChargeId,Day_Number,Vic_Count,Longitude,Latitude,Zone_int,Beat,DISTRICT,x,y
count,252188.000000,252188.000000,252188.000000,252188.000000,252188.000000,252188.000000,252188.000000,2.521880e+05,0.0,0.0,...,2.521380e+05,252138.000000,37849.000000,252138.000000,252138.000000,252127.00000,252127.000000,251899.000000,252138.000000,252138.000000
mean,23.215224,30314.358697,24.643730,21.138920,18.046334,29.281742,36704.411066,3.602114e+05,NaN,NaN,...,3.951184e+06,4.083367,1.163175,-84.407997,33.750213,3.36714,342.768914,6.205420,-84.407997,33.750213
std,3.620393,7.308327,4.208382,6.606441,10.387543,14.024707,15068.080625,1.463064e+05,NaN,NaN,...,1.109301e+06,1.992482,0.567198,0.038432,0.039982,1.70161,169.817494,3.803611,0.038432,0.039982
min,17.100000,30002.000000,20.000000,9.000000,0.000000,0.000000,6130.000000,2.217660e+05,NaN,NaN,...,1.446824e+06,1.000000,1.000000,-84.500712,33.634070,1.00000,101.000000,1.000000,-84.500712,33.634070
25%,20.400000,30311.000000,22.000000,17.000000,12.000000,25.000000,27365.000000,2.516770e+05,NaN,NaN,...,3.084930e+06,2.000000,1.000000,-84.432420,33.722086,2.00000,206.000000,3.000000,-84.432420,33.722086
50%,22.700000,30315.000000,23.000000,21.000000,15.000000,25.000000,33568.000000,3.910200e+05,NaN,NaN,...,3.984876e+06,4.000000,1.000000,-84.407643,33.750835,3.00000,309.000000,5.000000,-84.407643,33.750835
75%,25.200000,30318.000000,26.000000,24.000000,20.000000,38.000000,60392.000000,3.910200e+05,NaN,NaN,...,4.803969e+06,6.000000,1.000000,-84.380357,33.777405,5.00000,501.000000,9.000000,-84.380357,33.777405
max,39.900000,30354.000000,46.000000,59.000000,69.000000,100.000000,60392.000000,1.416243e+06,NaN,NaN,...,7.475809e+06,7.000000,14.000000,-84.291106,33.886053,7.00000,707.000000,12.000000,-84.291106,33.886053

In [8]:
sorted(final_merged_df['ZIP Code'].unique())

[np.int64(30002),
 np.int64(30030),
 np.int64(30032),
 np.int64(30033),
 np.int64(30303),
 np.int64(30305),
 np.int64(30306),
 np.int64(30307),
 np.int64(30308),
 np.int64(30309),
 np.int64(30310),
 np.int64(30311),
 np.int64(30312),
 np.int64(30313),
 np.int64(30314),
 np.int64(30315),
 np.int64(30316),
 np.int64(30317),
 np.int64(30318),
 np.int64(30319),
 np.int64(30324),
 np.int64(30327),
 np.int64(30329),
 np.int64(30337),
 np.int64(30339),
 np.int64(30342),
 np.int64(30344),
 np.int64(30345),
 np.int64(30354)]

In [11]:
print(final_merged_df['ZIP Code'].nunique())

29

In [13]:
final_merged_df.to_csv("all_merged.csv", index=False)